# Generated by Django 5.2.6 on 2025-11-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='interior_image',
            field=models.ImageField(blank=True, help_text='Interior view of the car', null=True, upload_to='cars/interior/'),
        ),
    ]
